api/src/Middleware/AuthMiddleware.php, api/tests/Middleware/AuthMiddlewareTest.php
Change status 400 -> 401
Change all message by `"message": "Unauthorized"`
Fix tests
=> [Issue-41]: Fix Unauthorized message

api/src/Controllers/RegisterController.php, api/src/Validator/RegexValidator.php, api/src/Validator/Validator.php
- Add `RegexValidator`
- New options system for validators
- Add a new rule to the `username` field
=> [Issue-40]: Add username length

api/src/Model/User.php, api/tests/Model/UserTest.php
=> [Issue-65]: Matches

api/composer.lock, api/src/Controllers/SearchProfileController.php, api/src/Resources/JsonResource.php, api/src/Resources/SearchableUserResource.php, api/src/Resources/UserResource.php
=> [Issue-63]: Model data rendering

api/composer.lock, frontend/src/App.vue, frontend/src/middlewares/auth.js, frontend/src/router/index.js, frontend/src/services/auth.js, frontend/src/utils/api.js
Fix `isAuthenticated` function, remove `async`
=> fix refresh token

frontend/src/services/socket.js, frontend/src/utils/api.js
Change `localhost` by `${location.hostname}`
=> Fix hostname in api request

api/composer.lock, docker-compose.yml
=> Add phpmyadmin docker image

frontend/src/components/Avatar.vue
=> Create avatar componant

api/composer.lock, api/src/Model/Model.php
=> fix canCreate

api/database/seeders/DatabaseSeeder.php
Add color and class seeder run
=> Add color in seeder

frontend/src/components/LoginForm.vue
When the login was performed, a codition check if the status code was equal to status 200 otherwise by default returns an “Unexpected error” except that when the login succeeds it does not return a response object but the JSON data.
- [n/a] Unit tests added (if applicable).
=> [Issue-94]: Fix Unexpected error in login

api/src/Model/User.php, api/tests/Model/UserTest.php
Age calculation was reversed (`d-m-Y` -> `Y-m-d`)
=> Fix User::getAge

.gitignore, api/composer.json, api/entrypoint_docker.sh
- `composer migrate`
- `composer seeder`
- `composer format`
- `composer test` -> `composer tests`
Add migrate to docker start
- [n/a] Unit tests added (if applicable).
- [n/a] The code formatted (e.g. with `npm run format`)
=> Add composer scripts

api/composer.lock, api/src/Exceptions/UniqueConstraintException.php, api/src/Model/Model.php, api/src/config.php, api/tests/Controllers/LikeControllerTest.php, api/tests/Controllers/RegisterControllerTest.php
Add `instanceof` in `config.php`
=> Fix 500 internal unique constraint

api/src/Controllers/Profile/ProfileController.php, frontend/src/views/UserProfile.vue
- Display if user profile does not exist
=> [Issue-121]: Profile not exist

frontend/src/router/index.js, frontend/src/views/UserProfileView.vue
- `UserProfile.vue` -> `UserProfileView.vue`
- If distance is `-1`, display `less of 1 km`
=> [Issue-112]: Add mimum distance in frontend

websocket/src/handlers/chat.js
Messages were not sent because the request was only made when the receiving user was logged in.
=> [Issue-128]: Messages not sent

frontend/src/App.vue, frontend/src/services/auth.js
- Display Navbar in login/logout
=> [Issue-129]: Login/Logout event

frontend/src/router/index.js, frontend/src/views/NotFound.vue
=> [Issue-137]: Add 404 page

api/composer.lock, docker-compose.yml
=> Fix error in dockerfile for `composer migrate`

api/src/Controllers/Profile/ProfileSuggestionController.php
- Change const by user distance preference
=> Use distance preference of user

api/Dockerfile, api/composer.json, api/composer.lock, api/entrypoint_docker.sh, api/src/Controllers/RegisterController.php, api/src/Services/Photo.php, api/src/routes.php
- Verify file extension
- Test create file by content
=> [Issue-153]: Protect photo format

frontend/index.html, frontend/src/views/HomeView.vue
- [n/a] Unit tests added (if applicable).
- [n/a] The code formatted (e.g. with `npm run format`)
=> remove: center color in HomeView.vue

frontend/src/App.vue, frontend/src/components/ThemeSwitcher.vue
- Theme save in localStorage
- [n/a] Unit tests added (if applicable).
=> feat: save changed theme

api/composer.lock, docker-compose.yml, frontend/src/plugins/socket.js, websocket/package-lock.json, websocket/package.json, websocket/src/database/database.ts, websocket/src/events/index.ts
=> Feat websocket db connection 

frontend/src/services/auth.js
=> close socket if logout
